FROM ubuntu:18.04

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt update && \
    apt upgrade -y && \
    apt install -y smokeping && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /var/run/smokeping

EXPOSE 80

CMD smokeping --nodaemon --config=/etc/smokeping/config

